### ISSUE TITLE
Svg is making positioning of elements misplaced

### ISSUE THREAD

**Issue by ppromsuban** [SurgeryWebby/Web-FrontEnd#12]
![screen shot 2561-11-09 at 01 01 16](https://user-images.githubusercontent.com/12114004/48217857-18d80580-e3bb-11e8-96d4-a4689bb5c01e.png)
![screen shot 2561-11-09 at 01 01 21](https://user-images.githubusercontent.com/12114004/48217858-19709c00-e3bb-11e8-8891-b31939f76537.png)

**Comment by minapapol** [comment]
fix on fix/svg-top-wave-css
